mod numbers;
mod chars;
mod booleans;
mod operators;
mod scope_and_shadowing;
mod constants;
mod stack_and_heap;
mod if_statement;
mod while_loop;
mod for_loop;
mod match_statement;
mod combination_lock;
mod structs;
mod enumerations;
mod unions;
mod option_t;
mod arrays;
mod slices;
mod tuples;
mod pattern_matching;
mod generics;
mod vectors;
mod hash_maps;
mod hash_sets;
mod iterators;
mod strings;
mod string_formatting;

pub use numbers::numbers;
pub use chars::chars;
pub use booleans::booleans;
pub use operators::operators;
pub use scope_and_shadowing::scope_and_shadowing;
pub use constants::constants;
pub use stack_and_heap::stack_and_heap;
pub use if_statement::if_statement;
pub use while_loop::while_loop;
pub use for_loop::for_loop;
pub use match_statement::match_statement;
pub use combination_lock::combination_lock;
pub use structs::structs;
pub use enumerations::enums;
pub use unions::unions;
pub use option_t::option_t;
pub use arrays::arrays;
pub use slices::slices;
pub use tuples::tuples;
pub use pattern_matching::pattern_matching;
pub use generics::generics;
pub use vectors::vectors;
pub use hash_maps::hash_maps;
pub use hash_sets::hash_sets;
pub use iterators::iterators;
pub use strings::strings;
pub use string_formatting::string_formatting;